// ---------------------------------------------------------------- //
// This file is autogenerated by pioasm version 2.2.0; do not edit! //
// ---------------------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ----- //
// df_tx //
// ----- //

#define df_tx_wrap_target 0
#define df_tx_wrap 8
#define df_tx_pio_version 0

static const uint16_t df_tx_program_instructions[] = {
            //     .wrap_target
    0x80a0, //  0: pull   block
    0xe081, //  1: set    pindirs, 1
    0xe300, //  2: set    pins, 0                [3]
    0xe03f, //  3: set    x, 31
    0x6701, //  4: out    pins, 1                [7]
    0x0044, //  5: jmp    x--, 4
    0xe701, //  6: set    pins, 1                [7]
    0xe080, //  7: set    pindirs, 0
    0x0000, //  8: jmp    0
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program df_tx_program = {
    .instructions = df_tx_program_instructions,
    .length = 9,
    .origin = -1,
    .pio_version = df_tx_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config df_tx_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + df_tx_wrap_target, offset + df_tx_wrap);
    return c;
}
#endif

