// ---------------------------------------------------------------- //
// This file is autogenerated by pioasm version 2.2.0; do not edit! //
// ---------------------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ----- //
// df_rx //
// ----- //

#define df_rx_wrap_target 0
#define df_rx_wrap 8
#define df_rx_pio_version 0

static const uint16_t df_rx_program_instructions[] = {
            //     .wrap_target
    0xe080, //  0: set    pindirs, 0
    0x2020, //  1: wait   0 pin, 0
    0xa442, //  2: nop                           [4]
    0xe03f, //  3: set    x, 31
    0x4701, //  4: in     pins, 1                [7]
    0x0044, //  5: jmp    x--, 4
    0x8020, //  6: push   block
    0x20a0, //  7: wait   1 pin, 0
    0x0000, //  8: jmp    0
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program df_rx_program = {
    .instructions = df_rx_program_instructions,
    .length = 9,
    .origin = -1,
    .pio_version = df_rx_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config df_rx_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + df_rx_wrap_target, offset + df_rx_wrap);
    return c;
}
#endif

